spring:
  application:
    name: SigeDoc
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: sigdoc
    password: sigdoc
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
